### ISSUE TITLE
Error when trying to use config file

### ISSUE THREAD

**Issue by ashBabu** [joshith/wolfinch#20]
Hi,
I tried to run ``` python3 Wolfinch.py --config config/cbpro_example.yml ```. It returns the following error

```
Traceback (most recent call last):
  File "/home/ash/Ash/repo/wolfinch/Wolfinch.py", line 349, in <module>
    Wolfinch_init()
  File "/home/ash/Ash/repo/wolfinch/Wolfinch.py", line 69, in Wolfinch_init
    exchanges.init_exchanges(get_config())
  File "/home/ash/Ash/repo/wolfinch/exchanges/exchanges_ops.py", line 39, in init_exchanges
    for exch in WolfinchConfig['exchanges']:
KeyError: 'exchanges'
```
Further I tried to change 'exchanges' with 'exchange', then it returned the following error

```
Traceback (most recent call last):
  File "/home/ash/Ash/repo/wolfinch/Wolfinch.py", line 349, in <module>
    Wolfinch_init()
  File "/home/ash/Ash/repo/wolfinch/Wolfinch.py", line 69, in Wolfinch_init
    exchanges.init_exchanges(get_config())
  File "/home/ash/Ash/repo/wolfinch/exchanges/exchanges_ops.py", line 40, in init_exchanges
    for name, exch_cfg in exch.items():
AttributeError: 'str' object has no attribute 'items'
```
@joshith : Is this a bug?

**Comment by joshith** [comment]
Looks like you are using wrong config file. There two kind of config files, one is where you configure the bot behavior, trading pair, exchanges etc. Other is the exchange config file, where you setup your authentication, keypairs etc for using particular exchange. The exchange config file generally goes inside the main config. 

You happened to use the exchange config file in place of main bot config file. 

here is a correct usage for cbpro. 
/Wolfinch.py --config config/wolfinch_cbpro_btc_backtest_sim.yml --import_only
./Wolfinch.py --config config/wolfinch_cbpro_btc_backtest_sim.yml

Be sure to check and verify the config file before running, you don't want to place trades in the live exchange first time you run :-)
